### ISSUE TITLE
Money pouch suggestion

### ISSUE THREAD

**Issue by SpaceMooo** [Runonstof/CustomNPCs-Scripting-Software#22]
![2019-05-10 - 19 43 45 ~ Cropped Capture](https://user-images.githubusercontent.com/50497808/57545907-f750da00-735b-11e9-89fc-9ecc8c075942.png)

If you click on the "deposit" text right now it still uses the old in hand deposit method, my suggestion is that you change it so it deposits all the money in your inventory. (It just makes more sense to me instead of it only depositing whats in your hand)

**Comment by Runonstof** [comment]
Will be fixed
